add english translation
aeraki-mesh/website pull request #10
Opened 2022-05-08 01:52 UTC by Albertchamberlain

2022-05-08 05:13 UTC, Albertchamberlain commented
#2 
#3

2022-05-08 06:18 UTC, zhaohuabing requested changes

2022-05-08 06:18 UTC, zhaohuabing commented on content/en/docs/v1.0/tutorials/local-rate-limit.md
> +## Installing the sample program
建议将 sample 改为 demo，以下同

2022-05-08 06:18 UTC, zhaohuabing commented on content/en/docs/v1.0/tutorials/local-rate-limit.md
> +You can choose any of the programs to test.
You can choose either of them to test.

2022-05-08 06:18 UTC, zhaohuabing commented on content/en/docs/v1.0/tutorials/local-rate-limit.md
> +Aeraki's flow restriction rules are designed to be intuitive and flexible, supporting both flow restriction for all inbound requests to a service and fine-grained flow restriction control for request
Flow restriction rule -> rate limiting rule

以下同

2022-05-08 06:18 UTC, zhaohuabing commented on content/en/docs/v1.0/tutorials/local-rate-limit.md
> +## Restrict the flow of all inbound requests to the service
Enforce rate limiting on all inbound requests of a service

2022-05-08 06:18 UTC, zhaohuabing commented on content/en/docs/v1.0/tutorials/local-rate-limit.md
> +> Note: Because local flow limiting is handled separately on each service instance, when the service has multiple instances, the actual flow limiting effect is the number of flow limiting times the n
local flow limiting -》local rate limiting

2022-05-08 06:18 UTC, zhaohuabing commented on content/en/docs/v1.0/tutorials/routing.md
> +Aeraki interprets the routing rules configured in the MetaRouter as routing rules for the MetaProtocol Proxy, and then distributes them to the MetaProtocol Proxy through Aeraki's built-in RDS serve
Aeraki translates MetaRouter to MetaProtocol route configuration, and then...

2022-05-08 06:22 UTC, Albertchamberlain commented
好的，修改后会提交

2022-05-08 06:36 UTC, zhaohuabing commented on content/en/docs/v1.0/tutorials/routing.md
> +## Installing the sample program
建议 sample 改为 demo，以下同

2022-05-08 06:37 UTC, zhaohuabing commented on content/en/docs/v1.0/tutorials/routing.md
> +You can choose any of the programs to test.
You can choose either of them to test.

2022-05-08 06:37 UTC, zhaohuabing commented on content/en/docs/v1.0/tutorials/routing.md
> +## Request-level load balance
load balance -> load balancing 
以下同

2022-05-08 06:45 UTC, zhaohuabing commented on content/en/docs/v1.0/tutorials/routing.md
> +Istio uses TCP proxy to proxy non-HTTP client requests, and all requests from the same client TCP connection are sent to a single server instance. This leads to a problem: when clients use long conne
and when the server side is overloaded, it cannot share the pressure on the existing server side even if it is scaled up in time.
建议： and when the server side is overloaded, the incoming requests that come through the existing connections can't be distributed to new instances even though more instances are added to the pool of the server cluster to share the load.

2022-05-08 06:46 UTC, zhaohuabing commented on content/en/docs/v1.0/tutorials/routing.md
> +Aeraki supports seven layers (request level) of load balancing for any protocol developed based on MetaProtocol, so without any configuration, the client's proxy sends requests evenly to two differen
Aeraki supports layer-7(request level) load balancing for ...

2022-05-08 06:48 UTC, zhaohuabing commented on content/en/docs/v1.0/tutorials/routing.md
> +## Routes requests to a specified version of the service by arbitrary properties
建议简化一下： Routes requests to a specified version based on arbitrary properties

2022-05-08 06:49 UTC, zhaohuabing commented on content/en/docs/v1.0/tutorials/routing.md
> +> Note: Aeraki will create Listener according to the VIP of the service, and each service will have its own Listener, which avoids the routing table expansion problem caused by multiple services on t
routing query -> route matching

2022-05-08 06:50 UTC, zhaohuabing commented on content/en/docs/v1.0/tutorials/routing.md
> +## Flow data splitting
Traffic splitting
以下同

2022-05-08 06:52 UTC, zhaohuabing commented on content/en/docs/v1.0/tutorials/routing.md
> +## Understand the principles
Understand what happened
其他翻译同

2022-05-08 06:53 UTC, zhaohuabing commented on content/en/docs/v1.0/tutorials/local-rate-limit.md
> +## Understand the principles
Understand what happened
其他翻译同

2022-05-09 01:40 UTC, zhaohuabing approved these changes
LGMT

2022-05-09 02:15 UTC, merged